### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by itse4elhaam** [heyman/leaflet-centermarker#2]
Kindly include an installation guide in the Readme, thanks

**Comment by itse4elhaam** [comment]
I am trying to get this to work in my react codebase, how should I approach this?

**Comment by heyman** [comment]
See the bundled [example](https://github.com/heyman/leaflet-centermarker/blob/master/example/index.html).

You'll have to figure out how to adopt it to your React codebase.

**Comment by itse4elhaam** [comment]
Yeah I did figure it out, but would recommend you to keep an adapter for react too.
